# Generated by Django 5.2 on 2025-05-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_terms_confirmed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="given_name",
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Nowak", max_length=255),
            preserve_default=False,
        ),
    ]
