# Generated by Django 5.2 on 2025-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_username_user_given_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                ],
                max_length=20,
            ),
        ),
    ]
