# Generated by Django 5.2 on 2025-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="default_images/default_avatar.png", upload_to="avatars/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                default="MALE",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
