# Generated by Django 5.2 on 2025-05-09 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="hint",
        ),
        migrations.RemoveField(
            model_name="task",
            name="question_text",
        ),
        migrations.CreateModel(
            name="TaskBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("LATEX", "Latex"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="task_blocks/"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
    ]
