# Generated by Django 5.2 on 2025-05-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_task_hint_remove_task_question_text_taskblock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="closedanswer",
            name="answer_text",
        ),
        migrations.AddField(
            model_name="closedanswer",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="closedanswer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="closed_answers/"),
        ),
        migrations.AddField(
            model_name="closedanswer",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="closedanswer",
            name="type",
            field=models.CharField(
                choices=[("TEXT", "Text"), ("IMAGE", "Image"), ("LATEX", "Latex")],
                default="TEXT",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
