# Generated by Django 5.2 on 2025-06-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_closedanswer_answer_text_closedanswer_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskblock",
            name="inline",
            field=models.BooleanField(default=False),
        ),
    ]
