# Generated by Django 5.2 on 2025-08-14 00:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("homeworks", "0005_rename_homework_homeworkorm_and_more"),
        ("tasks", "0006_taskblock_inline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClosedAnswer",
            new_name="ClosedAnswerOrm",
        ),
        migrations.RenameModel(
            old_name="TaskBlock",
            new_name="TaskBlockOrm",
        ),
        migrations.RenameModel(
            old_name="Task",
            new_name="TaskOrm",
        ),
    ]
