# Generated by Django 5.2 on 2026-07-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_rename_closedanswer_closedanswerorm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskorm",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("WAITING_ACCEPT", "Waiting Accept"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
