# Generated by Django 5.2 on 2025-08-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("tasks", "0007_rename_closedanswer_closedanswerorm_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="CategoryOrm",
        ),
    ]
