# Generated by Django 5.2 on 2025-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_avatar_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="assets/default_images/default_avatar.png", upload_to="avatars/"
            ),
        ),
    ]
