# Generated by Django 5.2 on 2025-08-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("homeworks", "0005_rename_homework_homeworkorm_and_more"),
        ("tasks", "0007_rename_closedanswer_closedanswerorm_and_more"),
        ("users", "0007_rename_user_userorm"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserOrm",
            new_name="User",
        ),
    ]
