# Generated by Django 5.2 on 2025-05-04 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="correct_answer",
        ),
        migrations.AddField(
            model_name="task",
            name="hint",
            field=models.TextField(
                blank=True, help_text="Opcjonalna podpowiedź dla ucznia.", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClosedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closed_answers",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
    ]
