# Generated by Django 5.2 on 2025-05-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("READY", "Ready"),
                    ("SUBMITTED", "Submitted"),
                    ("CHECKED", "Checked"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
