# Generated by Django 5.2 on 2025-05-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0002_homework_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data sprawdzenia rozwiązania przez nauczyciela.",
                null=True,
            ),
        ),
    ]
