# Generated by Django 5.2 on 2025-06-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0003_homework_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="ready_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data oznaczenia zadania jako do zrobienia.",
                null=True,
            ),
        ),
    ]
