# Generated by Django 5.2 on 2025-08-13 23:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0004_homework_ready_at"),
        ("tasks", "0006_taskblock_inline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Homework",
            new_name="HomeworkOrm",
        ),
        migrations.RenameModel(
            old_name="HomeworkTask",
            new_name="HomeworkTaskOrm",
        ),
    ]
